name: Main tests

on:
  push:
    branches:
      - develop
      - main
      - master
  pull_request:

jobs:
  all_functionality:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setting up Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_ci.txt
          git clone https://github.com/cvg/lightglue
          python -m pip install lightglue/

      - name: Run main tests
        run: python -m pytest tests/